CREATE DATABASE slac

CREATE TABLE coordenador_ac (
  id_admin SERIAL NOT NULL,
  nome_admin VARCHAR(40) NOT NULL,
  login VARCHAR(20) NOT NULL,
  senha VARCHAR(8) NOT NULL,
  PRIMARY KEY (id_admin));

CREATE TABLE Aluno (
  id_aluno SERIAL NOT NULL,
  cpf INTEGER NOT NULL,
  nome VARCHAR(40) NOT NULL,
  senha VARCHAR(8) NOT NULL,
  email VARCHAR(30) NOT NULL,
  matricula INTEGER NOT NULL,
  ano_ingresso YEAR NOT NULL,
  permissao BOOLEAN NOT NULL,
  coordenador_ac_id_admin INTEGER NULL,
  PRIMARY KEY (id_aluno),
  CONSTRAINT fk_aluno_coordenador_ac FOREIGN KEY (coordenador_ac_id_admin) REFERENCES coordenador_ac (id_admin)
  );
  
CREATE TABLE modalidade (
  id_mod INTEGER NOT NULL,
  nome_mod VARCHAR(50) NOT NULL,
  PRIMARY KEY (id_mod));
  
CREATE TABLE atividade_complementar (
  id_atividade SERIAL NOT NULL,
  descricao_ac VARCHAR(100) NOT NULL,
  ch_max_ac INTEGER NULL,
  ch_min_ac INTEGER NULL,
  modalidade_id_mod INTEGER NOT NULL,
  PRIMARY KEY (id_atividade),
  CONSTRAINT fk_atividade_complementar_modalidade FOREIGN KEY (modalidade_id_mod) REFERENCES modalidade (id_mod)
  );

  CREATE TABLE participacao (
  atividade_complementar_id_atividade INTEGER NOT NULL,
  aluno_id_aluno INTEGER NOT NULL,
  id_Participacao INTEGER NOT NULL,
  certificado_part VARCHAR(70) NOT NULL,
  coordenador_ac_id_admin INTEGER NULL,
  status VARCHAR(25) NOT NULL,
  data_validacao_ac DATE NULL,
  nome_ac_part VARCHAR(50) NOT NULL,
  data_inicio_ac_part DATE NOT NULL,
  ch_cadastrada_part DECIMAL(10,0) NOT NULL,
  ch_validada_part DECIMAL(10,0) NOT NULL,
  Local_ac_part VARCHAR(60) NOT NULL,
  Tipo_ac_part VARCHAR(15) NOT NULL,
  PRIMARY KEY (Atividade_Complementar_Id_atividade, Aluno_Id_aluno, Id_Participacao),
  INDEX fk_Atividade_Complementar_has_Aluno_Aluno1_idx (Aluno_Id_aluno ASC),
  INDEX fk_Atividade_Complementar_has_Aluno_Atividade_Complementar1_idx (Atividade_Complementar_Id_atividade ASC),
  INDEX fk_Atividade_Complementar_has_Aluno_Coordenador_AC1_idx (Coordenador_AC_Id_admin ASC),
  CONSTRAINTEGER fk_Atividade_Complementar_has_Aluno_Atividade_Complementar1
    FOREIGN KEY (Atividade_Complementar_Id_atividade)
    REFERENCES mydb.Atividade_Complementar (Id_atividade)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINTEGER fk_Atividade_Complementar_has_Aluno_Aluno1
    FOREIGN KEY (Aluno_Id_aluno)
    REFERENCES mydb.Aluno (CPF)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINTEGER fk_Atividade_Complementar_has_Aluno_Coordenador_AC1
    FOREIGN KEY (Coordenador_AC_Id_admin)
    REFERENCES mydb.Coordenador_AC (Id_admin)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
CREATE TABLE aluno(
	id_aluno serial NOT NULL,
	cpf INTEGEReger,
	nome varchar(40),
	senha varchar(8),
	email varchar(30),
	matricula INTEGEReger,
	ano_ingresso YEAR,
	permissao boolean,
	coordenador_ac_id_admin,
)


CREATE TABLE amigo
(
  idamigo serial NOT NULL,
  nome character varying(100),
  raca character varying(100),
  tipo_idtipo INTEGEReger,
  CONSTRAINTEGER amigo_pkey PRIMARY KEY (idamigo)
);

create table amigo_telefone(
	idamigotelefone serial not null,
	amigo_idamigo INTEGEReger not null,
	numero_telefone varchar(20),	
	primary key(idamigotelefone)
	
	);

-- MySQL Script generated by MySQL Workbench
-- 02/14/18 14:45:11
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS mydb DEFAULT CHARACTER SET utf8 ;
USE mydb ;

-- -----------------------------------------------------
-- Table mydb.Coordenador_AC
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS mydb.Coordenador_AC (
  Id_admin INTEGER NOT NULL,
  Nome_admin VARCHAR(40) NOT NULL,
  Login VARCHAR(20) NOT NULL,
  Senha VARCHAR(8) NOT NULL,
  PRIMARY KEY (Id_admin))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table mydb.Aluno
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS mydb.Aluno (
  Id_aluno INTEGER NOT NULL,
  CPF INTEGER NOT NULL,
  Nome VARCHAR(40) NOT NULL,
  Senha VARCHAR(8) NOT NULL,
  E-mail VARCHAR(30) NOT NULL,
  Matricula INTEGER NOT NULL,
  Ano_ingresso YEAR NOT NULL,
  Permissao TINYINTEGER(1) NOT NULL,
  Coordenador_AC_Id_admin INTEGER NULL,
  INDEX fk_Aluno_Coordenador_AC1_idx (Coordenador_AC_Id_admin ASC),
  PRIMARY KEY (Id_aluno),
  CONSTRAINTEGER fk_Aluno_Coordenador_AC1
    FOREIGN KEY (Coordenador_AC_Id_admin)
    REFERENCES mydb.Coordenador_AC (Id_admin)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table mydb.Modalidade
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS mydb.Modalidade (
  Id_mod INTEGER NOT NULL,
  Nome_mod VARCHAR(50) NOT NULL,
  PRIMARY KEY (Id_mod))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table mydb.Atividade_Complementar
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS mydb.Atividade_Complementar (
  Id_atividade INTEGER NOT NULL,
  Descricao_ac VARCHAR(100) NOT NULL,
  CH_max_ac INTEGER NULL,
  CH_min_ac INTEGER NULL,
  Modalidade_Id_mod INTEGER NOT NULL,
  PRIMARY KEY (Id_atividade),
  INDEX fk_Atividade_Complementar_Modalidade1_idx (Modalidade_Id_mod ASC),
  CONSTRAINTEGER fk_Atividade_Complementar_Modalidade1
    FOREIGN KEY (Modalidade_Id_mod)
    REFERENCES mydb.Modalidade (Id_mod)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table mydb.Participacao
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS mydb.Participacao (
  Atividade_Complementar_Id_atividade INTEGER NOT NULL,
  Aluno_Id_aluno INTEGER NOT NULL,
  Id_Participacao INTEGER NOT NULL,
  Certificado_part VARCHAR(70) NOT NULL,
  Coordenador_AC_Id_admin INTEGER NULL,
  status VARCHAR(25) NOT NULL,
  Data_validacao_ac DATE NULL,
  Nome_ac_part VARCHAR(50) NOT NULL,
  Data_inicio_ac_part DATE NOT NULL,
  Ch_cadastrada_part DECIMAL(10,0) NOT NULL,
  Ch_validada_part DECIMAL(10,0) NOT NULL,
  Local_ac_part VARCHAR(60) NOT NULL,
  Tipo_ac_part VARCHAR(15) NOT NULL,
  PRIMARY KEY (Atividade_Complementar_Id_atividade, Aluno_Id_aluno, Id_Participacao),
  INDEX fk_Atividade_Complementar_has_Aluno_Aluno1_idx (Aluno_Id_aluno ASC),
  INDEX fk_Atividade_Complementar_has_Aluno_Atividade_Complementar1_idx (Atividade_Complementar_Id_atividade ASC),
  INDEX fk_Atividade_Complementar_has_Aluno_Coordenador_AC1_idx (Coordenador_AC_Id_admin ASC),
  CONSTRAINTEGER fk_Atividade_Complementar_has_Aluno_Atividade_Complementar1
    FOREIGN KEY (Atividade_Complementar_Id_atividade)
    REFERENCES mydb.Atividade_Complementar (Id_atividade)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINTEGER fk_Atividade_Complementar_has_Aluno_Aluno1
    FOREIGN KEY (Aluno_Id_aluno)
    REFERENCES mydb.Aluno (CPF)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINTEGER fk_Atividade_Complementar_has_Aluno_Coordenador_AC1
    FOREIGN KEY (Coordenador_AC_Id_admin)
    REFERENCES mydb.Coordenador_AC (Id_admin)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
